#!/usr/bin/env python3
"""Build a static Rime dictionary from delayed-learning commit logs.

The generated dictionary is only consumed after the user redeploys Rime, so
ranking work never runs in the key-processing path.
"""

from __future__ import annotations

import argparse
import collections
import datetime as dt
from pathlib import Path

HEADER = """# Rime dictionary
# encoding: utf-8
# Generated by tools/build_delayed_ranking.py; do not edit manually.
---
name: wubi86_jidian_delayed
version: \"{version}\"
sort: by_weight
use_preset_vocabulary: false
...
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build delayed Rime ranking dictionary")
    parser.add_argument("--log", type=Path, required=True, help="TSV log created by the Lua recorder")
    parser.add_argument("--output", type=Path, required=True, help="Output wubi86_jidian_delayed.dict.yaml")
    parser.add_argument("--min-count", type=int, default=3, help="Ignore candidates used fewer times (default: 3)")
    parser.add_argument("--base-weight", type=int, default=100000, help="Base static weight")
    parser.add_argument("--step", type=int, default=1000, help="Weight added for each committed use")
    parser.add_argument("--max-entries", type=int, default=5000, help="Maximum generated entries")
    return parser.parse_args()


def load_counts(path: Path) -> collections.Counter[tuple[str, str]]:
    counts: collections.Counter[tuple[str, str]] = collections.Counter()
    if not path.exists():
        return counts

    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) != 3:
                continue
            _, text, code = parts
            text, code = text.strip(), code.strip().lower()
            if not text or not code or len(code) > 32:
                continue
            if any(ch not in "abcdefghijklmnopqrstuvwxyz'" for ch in code):
                continue
            counts[(text, code)] += 1
    return counts


def main() -> int:
    args = parse_args()
    if args.min_count < 1 or args.step < 1 or args.max_entries < 1:
        raise SystemExit("min-count, step and max-entries must be positive")

    counts = load_counts(args.log)
    selected = [
        (text, code, count)
        for (text, code), count in counts.items()
        if count >= args.min_count
    ]
    selected.sort(key=lambda item: (-item[2], item[1], item[0]))
    selected = selected[: args.max_entries]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    version = dt.datetime.now().strftime("%Y.%m.%d.%H%M")
    with args.output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(HEADER.format(version=version))
        for text, code, count in selected:
            weight = args.base_weight + count * args.step
            handle.write(f"{text}\t{code}\t{weight}\n")

    print(f"generated {len(selected)} entries from {sum(counts.values())} commits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
